from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol
from uuid import UUID

from junto.domain.entities import Room


class RoomRepository(Protocol):
  def add(self, room: Room) -> None: ...

  def get(self, room_id: UUID) -> Room | None: ...

  def get_by_join_code(self, join_code: str) -> Room | None: ...

  def transaction(self, room_id: UUID) -> AbstractContextManager[Room]: ...

  def ping(self) -> bool: ...

  def delete(self, room_id: UUID) -> bool: ...

  def delete_expired(self, *, before: datetime, answering_before: datetime) -> int: ...

  def recover_stale_analyses(self, *, before: datetime, failed_at: datetime) -> int: ...
